### ISSUE TITLE
Improve documentation with 'DerivingVia` note

### ISSUE THREAD

**Issue by chshersh** [int-index/unwrapped-functors#1]
`DerivingVia` extension from GHC-8.6.1 can be used to avoid boilerplate for writing instances for `newtype`s. For example, the following works:

```haskell
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DeriveFunctor #-}

newtype Foo a = Foo a
  deriving (Functor)
  deriving Unwrappable via (Identity)
```

If you don't require your data type to be `Functor` you can even write something like this:

```haskell
class Newtype t where
  type Un t
  un :: t -> Un t
  wr :: Un t -> t

instance Newtype (Identity a) where
  type Un (Identity a) = a
  un = runIdentity
  wr = Identity

newtype Bar = Bar Int
  deriving Newtype via (Identity Int)
```

Looks like this opens a lot of opportunities for writing general purpose functions for `newtype` like:

```haskell
over :: Newtype t => (Un t -> Un t) -> t -> t
over f = wr . f . un
```

**Comment by int-index** [comment]
1. Yes, `DerivingVia` can be used for this, but it's just a natural use of this feature, not specific to this library. So why should this library in particular add it to its docs? Or do you expect every library to mention `DerivingVia` in docs for every class. Maybe it's a good idea, maybe not, I'm inclined to think it's not.

2. Initially I didn't have this superclass, but writing an instance for `Compose` exposed to me that I generally expect every `Unwrappable` to be a `Functor`.
